import { z } from "zod";
import { requestStatusSchema, sectionSchema } from "../enums";
import { getSymptomCategory, validateSymptomAnswers } from "../symptoms";
import { moneySchema, paginationQuerySchema } from "./common";
import { serviceCatalogItemSchema } from "./catalogue";
import { vehicleSummarySchema } from "./vehicle";

/** Answers keyed by question id. Stored in the symptomDetails Json column. */
export const symptomAnswersSchema = z.record(
  z.string().min(1).max(60),
  z.union([z.string().max(2000), z.array(z.string().max(120)).max(20)]),
);

const baseBookingFields = {
  vehicleId: z.uuid({ message: "Choose a vehicle." }),
  section: sectionSchema,
  symptomCategory: z.string().min(1, "Choose what the problem relates to."),
  symptomDetails: symptomAnswersSchema,
  serviceCatalogItemIds: z.array(z.uuid()).max(10).default([]),
  preferredDateTime: z.iso.datetime({ message: "Choose a date and time." }),
  locationText: z
    .string()
    .trim()
    .min(3, "Tell us where the vehicle will be.")
    .max(200, "Keep the location under 200 characters."),
  latitude: z.number().min(-90).max(90).nullable().optional(),
  longitude: z.number().min(-180).max(180).nullable().optional(),
};

/**
 * The category has to belong to the section it was booked under, and the
 * answers have to match the questions that category actually asks. Both apply
 * on the server and in the wizard, from this one definition.
 */
function checkSymptoms(
  value: {
    section: z.infer<typeof sectionSchema>;
    symptomCategory: string;
    symptomDetails: Record<string, string | string[]>;
  },
  ctx: z.RefinementCtx,
): void {
  const category = getSymptomCategory(value.symptomCategory);

  if (!category) {
    ctx.addIssue({
      code: "custom",
      path: ["symptomCategory"],
      message: "That is not a category we work on.",
    });
    return;
  }

  if (category.section !== value.section) {
    ctx.addIssue({
      code: "custom",
      path: ["symptomCategory"],
      message: "That category belongs to the other section.",
    });
    return;
  }

  for (const [questionId, message] of Object.entries(
    validateSymptomAnswers(category, value.symptomDetails),
  )) {
    ctx.addIssue({ code: "custom", path: ["symptomDetails", questionId], message });
  }
}

export const createServiceRequestSchema = z
  .object({
    ...baseBookingFields,
    /**
     * Generated by the client before the request leaves the device, so a
     * booking made offline and flushed twice still creates one record.
     */
    clientRequestId: z.uuid({ message: "Not a valid client request identifier." }),
  })
  .superRefine(checkSymptoms);
export type CreateServiceRequest = z.infer<typeof createServiceRequestSchema>;

/** The owner may correct a booking, but only while it is still SUBMITTED. */
export const updateServiceRequestSchema = z
  .object(baseBookingFields)
  .omit({ section: true })
  .partial()
  .refine((value) => Object.keys(value).length > 0, {
    message: "Send at least one field to change.",
  });
export type UpdateServiceRequest = z.infer<typeof updateServiceRequestSchema>;

export const updateStatusSchema = z.object({
  status: requestStatusSchema,
  note: z.string().trim().max(500, "Keep the note under 500 characters.").optional(),
  /**
   * Sent by staff when moving a booking to awaiting approval. This is the
   * figure the customer sees before they say yes, which is what stops the
   * argument at handover.
   */
  estimatedCost: z
    .string()
    .trim()
    .regex(/^\d{1,8}(\.\d{1,2})?$/, "Enter an amount, for example 450.00.")
    .optional(),
});
export type UpdateStatusRequest = z.infer<typeof updateStatusSchema>;

/**
 * The two moves a customer is allowed to make themselves, both only from
 * awaiting approval: approve the estimate, or decline and cancel.
 */
export const CLIENT_ALLOWED_TRANSITIONS: Readonly<
  Record<string, readonly ["IN_PROGRESS", "CANCELLED"] | undefined>
> = {
  AWAITING_APPROVAL: ["IN_PROGRESS", "CANCELLED"],
};

export function clientMayTransition(from: string, to: string): boolean {
  return CLIENT_ALLOWED_TRANSITIONS[from]?.some((allowed) => allowed === to) ?? false;
}

export const clientSummarySchema = z.object({
  id: z.uuid(),
  fullName: z.string(),
  phone: z.string(),
});
export type ClientSummary = z.infer<typeof clientSummarySchema>;

export const assignedStaffSummarySchema = z.object({
  id: z.uuid(),
  fullName: z.string(),
  section: sectionSchema.nullable(),
});

export const jobSummarySchema = z.object({
  id: z.uuid(),
  status: z.enum(["ASSIGNED", "IN_PROGRESS", "COMPLETED"]),
  assignedStaff: assignedStaffSummarySchema,
  startedAt: z.iso.datetime().nullable(),
  completedAt: z.iso.datetime().nullable(),
});

export const statusEventSchema = z.object({
  id: z.uuid(),
  fromStatus: requestStatusSchema.nullable(),
  toStatus: requestStatusSchema,
  note: z.string().nullable(),
  createdAt: z.iso.datetime(),
});
export type StatusEvent = z.infer<typeof statusEventSchema>;

export const serviceRequestSchema = z.object({
  id: z.uuid(),
  /** Short human readable code, so a job can be quoted over the phone. */
  reference: z.string(),
  clientId: z.uuid(),
  vehicleId: z.uuid(),
  section: sectionSchema,
  status: requestStatusSchema,
  preferredDateTime: z.iso.datetime(),
  locationText: z.string(),
  latitude: z.number().nullable(),
  longitude: z.number().nullable(),
  symptomCategory: z.string(),
  symptomDetails: symptomAnswersSchema,
  estimatedCost: moneySchema.nullable(),
  clientRequestId: z.uuid(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
  vehicle: vehicleSummarySchema,
  client: clientSummarySchema,
  requestedServices: z.array(serviceCatalogItemSchema),
  job: jobSummarySchema.nullable(),
});
export type ServiceRequest = z.infer<typeof serviceRequestSchema>;

export const serviceRequestListQuerySchema = paginationQuerySchema.extend({
  status: requestStatusSchema.optional(),
  section: sectionSchema.optional(),
  vehicleId: z.uuid().optional(),
  search: z.string().trim().min(1).max(60).optional(),
});
export type ServiceRequestListQuery = z.infer<typeof serviceRequestListQuerySchema>;

export const serviceRequestResponseSchema = z.object({ serviceRequest: serviceRequestSchema });
export const serviceRequestListResponseSchema = z.object({
  data: z.array(serviceRequestSchema),
  meta: z.object({
    page: z.number().int(),
    limit: z.number().int(),
    total: z.number().int(),
    totalPages: z.number().int(),
  }),
});
export type ServiceRequestListResponse = z.infer<typeof serviceRequestListResponseSchema>;

export const timelineResponseSchema = z.object({ data: z.array(statusEventSchema) });
export type TimelineResponse = z.infer<typeof timelineResponseSchema>;

/**
 * Reference code derived from the record id, so it needs no column and never
 * drifts from the row it names. Shown in mono, quoted over the phone.
 */
export function referenceFromId(id: string): string {
  return `CH-${id.replace(/-/g, "").slice(0, 6).toUpperCase()}`;
}
